Generating new random routes...
Starting Webots on hostname
Warning: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/local_scratch/pbs.3622233[4].pbs02/runtime-mwfranc'
Info: Sandboxing disabled by user.
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
ERROR: Cannot initialize the sound engine: Cannot initialize OpenAL default device 'OpenAL Soft'
ERROR: Cannot initialize the sound engine: Cannot initialize OpenAL default device 'OpenAL Soft'
ERROR: Cannot initialize the sound engine: Cannot initialize OpenAL default device 'OpenAL Soft'
INFO: sumo_supervisor: Starting controller: python3 -u sumo_supervisor.py --no-gui --no-netconvert --max-vehicles=100 --port=8877 --seed=0 --step=50 --radius=-1 --maximum-lateral-speed=2.5 --maximum-angular-speed=3 --lane-change-delay=3
INFO: av_m_controller: Starting controller: python3 -u av_m_controller.py
Connect to SUMO... This operation may take a few seconds.
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
ERROR: Cannot initialize the sound engine: Cannot initialize OpenAL default device 'OpenAL Soft'
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
ERROR: Cannot initialize the sound engine: Cannot initialize OpenAL default device 'OpenAL Soft'
Blind Factor: -0.7877046446781303   Distance :  1.0  speed :  0.08691859392733543  theta: -0.7877046446781303
Blind Factor: 5.513046649153928   Distance :  10.806802541391642  speed :  2.192389290119587  theta: 0.5101459592731661
Blind Factor: -11.81182400407818   Distance :  14.694214351256518  speed :  -6.262220339524999  theta: -0.8038418197614041
Blind Factor: -0.7942519186660254   Distance :  1.0  speed :  0.6106148753514701  theta: -0.7942519186660254
Blind Factor: 5.677505751407268   Distance :  10.900574889902604  speed :  2.8587103762197255  theta: 0.5208446167978207
Blind Factor: -11.737519455822122   Distance :  14.455089999869225  speed :  -6.016457096272995  theta: -0.811999057489667
Blind Factor: -0.9080114281699628   Distance :  1.189451444734347  speed :  -0.017792550674885995  theta: -0.7633867125805701
Blind Factor: 6.532623473518341   Distance :  11.106022276651084  speed :  2.0322460480068716  theta: 0.5882055078578675
Blind Factor: -11.735228706564586   Distance :  14.92093610699469  speed :  -5.698409017445205  theta: -0.7864941329695329
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
ERROR: Cannot initialize the sound engine: Cannot initialize OpenAL default device 'OpenAL Soft'
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
ERROR: Cannot initialize the sound engine: Cannot initialize OpenAL default device 'OpenAL Soft'
Traceback (most recent call last):
  File "av_m_controller.py", line 527, in <module>
    risk_data_df.to_csv(proj_cwd + r"/output/data_"+timestamp+"_"+random_file_flag+
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 3386, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/formats/format.py", line 1083, in to_csv
    csv_formatter.save()
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/formats/csvs.py", line 228, in save
    with get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/mwfranc/Webots.HPC/Simulations/output/data_1632414518_604045_False.csv'
WARNING: 'av_m_controller' controller exited with status: 1.
Warning: The X11 connection broke: I/O error (code 1)
XIO:  fatal IO error 0 (Success) on X server ":99"
      after 25619 requests (25619 known processed) with 0 events remaining.
 
 
+------------------------------------------+ 
| PALMETTO CLUSTER PBS RESOURCES REQUESTED | 
+------------------------------------------+ 
 
mem=93gb,walltime=00:45:00,ncpus=5
 
 
+-------------------------------------+ 
| PALMETTO CLUSTER PBS RESOURCES USED | 
+-------------------------------------+ 
 
cput=00:54:50,mem=2795724kb,walltime=00:28:28,ncpus=5,cpupercent=185,vmem=21402588kb
 
 
